#!/usr/bin/env bash

set -euo pipefail

source $(realpath $(dirname "$0"))/common-clang.sh

if ! command -v clang-tidy >/dev/null 2>&1; then
    echo "clang-tidy could not be found"
    exit 1
fi

if ! command -v run-clang-tidy >/dev/null 2>&1; then
    echo "run-clang-tidy could not be found"
    exit 1
fi

clang-tidy ${FILES[@]} -p $BASE_DIR/../build --exclude-header-filter=".*build.*" --warnings-as-errors="*"
