#!/usr/bin/env bash

set -euo pipefail

if ! command -v clang-tidy >/dev/null 2>&1; then
    echo "clang-tidy could not be found"
    exit 1
fi

if ! command -v run-clang-tidy >/dev/null 2>&1; then
    echo "run-clang-tidy could not be found"
    exit 1
fi

run-clang-tidy -warnings-as-errors "*"
